server:
  address: 0.0.0.0
  port: 80
  error:
    include-message: always

spring:
  profiles:
    active: 'local'
    include:  'application-${spring.profiles.active}.yml'
  datasource:
    url: 'jdbc:postgresql://localhost:5432/postgres'
    username: ''
    password: ''
  jpa:
    hibernate:
      ddl-auto: 'validate'
    properties:
      hibernate:
        dialect: 'org.hibernate.dialect.PostgreSQLDialect'
        format_sql: true
    show-sql: true