version: '3'

services:
  postgresql-db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10

volumes:
  pgdata: